FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv  # Required to create virtual environments

# Create a virtual environment
RUN python3 -m venv /home/doc-bd-a1/venv

# Activate the virtual environment and install packages
RUN /home/doc-bd-a1/venv/bin/pip install pandas numpy seaborn matplotlib scikit-learn scipy

RUN mkdir -p /home/doc-bd-a1/

COPY Titanic.csv /home/doc-bd-a1/

COPY load.py dpre.py eda.py vis.py model.py final.sh /home/doc-bd-a1/

WORKDIR /home/doc-bd-a1/

# Activate the virtual environment when running the container
CMD ["/bin/bash", "-c", "source /home/doc-bd-a1/venv/bin/activate && /bin/bash"]